# -*- coding: utf-8 -*-

#Dicionários para padronizar os produtos do IBGE para o padrão do projeto
#NOTE: É comum que o nome dos produtos seja acompanhado de 
#NOTE: informações adicionais entre parênteses, como "semente", "fruto", etc.
#! Defini o padrão  {produto}-{informação adicional}

#NOTE: Quando existem produtos com especificações diferentes
#ex. PAM : Erva-mate (folha verde)
#ex. Censo Agro 2006 - 2017 : Erva-mate
#A padronização do nome foi feita considerando o censo como referência


### EXTRAÇÃO VEGETAL
dicionario_produtos_pevs = {
    '1 - Alimentícios': '1-alimentícios',
    '1.1 - Açaí (fruto)': 'açaí-fruto',
    '1.10 - Outros': 'outros alimentícios',
    '1.2 - Castanha-de-caju': 'castanha de caju',
    '1.3 - Castanha-do-pará': 'castanha do pará',
    '1.4 - Erva-mate': 'erva-mate',
    '1.5 - Mangaba (fruto)': 'mangaba-fruto',
    '1.6 - Palmito': 'palmito',
    '1.7 - Pequi (fruto)': 'pequi-fruto',
    '1.8 - Pinhão': 'pinhão',
    '1.9 - Umbu (fruto)': 'umbu',
    '10 - Tanantes': '10-tanantes',
    '10.1 - Angico (casca)': 'angico-casca',
    '10.2 - Barbatimão (casca)': 'barbatimão-casca',
    '10.3 - Outros': 'outros tanantes',
    '2 - Aromáticos, medicinais, tóxicos e corantes': '2-aromáticos, medicinais e corantes',
    '2.1 - Ipecacuanha ou poaia (raiz)': 'ipecacuanha-raiz',
    '2.2 - Jaborandi (folha)': 'jaborandi',
    '2.3 - Urucum (semente)': 'urucum',
    '2.4 - Outros': 'outros aromáticos, medicinais e corantes',
    '3 - Borrachas': '3-borrachas',
    '3.1 - Caucho': 'caucho',
    '3.2 - Hevea (látex coagulado)': 'borracha-latéx coagulado',
    '3.3 - Hevea (látex líquido)': 'borracha-latéx líquido',
    '3.4 - Mangabeira': 'mangabeira',
    '4 - Ceras': '4-ceras',
    '4.1 - Carnaúba (cera)': 'carnaúba-cera',
    '4.2 - Carnaúba (pó)': 'carnaúba-pó',
    '4.3 - Outras': 'outras ceras',
    '5 - Fibras': '5-fibras',
    '5.1 - Buriti': 'buriti',
    '5.2 - Carnaúba': 'carnaúba',
    '5.3 - Piaçava': 'piaçava',
    '5.4 - Outras': 'outras fibras',
    '6 - Gomas não elásticas': '6-gomas não elásticas',
    '6.1 - Balata': 'balata',
    '6.2 - Maçaranduba': 'maçaranduba',
    '6.3 - Sorva': 'sorva',
    '7.1 - Carvão vegetal': 'carvão vegetal',
    '7.2 - Lenha': 'lenha',
    '7.3 - Madeira em tora': 'madeira-tora',
    '8 - Oleaginosos': '8-oleaginosos',
    '8.1 - Babaçu (amêndoa)': 'babaçu-amêndoa',
    '8.2 - Copaíba (óleo)': 'copaíba-óleo',
    '8.3 - Cumaru (amêndoa)': 'cumaru-amêndoa',
    '8.4 - Licuri (coquilho)': 'licuri-coquilho',
    '8.5 - Oiticica (semente)': 'oiticica',
    '8.6 - Pequi (amêndoa)': 'pequi-amêndoa',
    '8.7 - Tucum (amêndoa)': 'tucum-amêndoa',
    '8.8 - Outros': 'outros oleaginosos',
    '9.1 - Pinheiro brasileiro (nó de pinho)': 'pinheiro brasileiro-nó de pinho',
    '9.2 - Pinheiro brasileiro (árvores abatidas)': 'pinheiro brasileiro-árvores abatidas',
    '9.3 - Pinheiro brasileiro (madeira em tora)': 'pinheiro brasileiro-madeira em tora',
    'Total': 'total'
}

dicionario_produtos_censo_6949_2233 = {
    'Andiroba (semente)': 'andiroba-semente',
    'Araticum (fruto)': 'araticum-fruto',
    'Açaí (fruto)': 'açaí-fruto',
    'Babaçu (amêndoa)': 'babaçu-amêndoa',
    'Babaçu (coco)': 'babaçu-coco',
    'Bacaba (fruto)': 'bacaba-fruto',
    'Bacuri': 'bacuri',
    'Baru (amêndoa)': 'baru-amêndoa',
    'Borracha (látex coagulado)': 'borracha-latéx coagulado',
    'Borracha (látex líquido)': 'borracha-latéx líquido',
    'Buriti (coco)': 'buriti-coco',
    'Buriti (palha)': 'buriti-palha',
    'Butiá (fibra)': 'butiá-fibra',
    'Cacau (amêndoa)': 'cacau-amêndoa',
    'Cagaita (fruto)': 'cagaita-fruto',
    'Cajarana': 'cajarana',
    'Camu-camu (fruto)': 'camu camu-fruto',
    'Carnaúba (cera)': 'carnaúba-cera',
    'Carnaúba (pó de palha) - Kg': 'carnaúba-pó de palha',
    'Casca de angico': 'angico-casca',
    'Castanha-do-Brasil (castanha-do-Pará)': 'castanha do pará',
    'Caucho (goma elástica)': 'caucho-goma elástica',
    'Copaíba (óleo)': 'copaíba-óleo',
    'Cumaru (semente)': 'cumaru-semente',
    'Cupuaçu': 'cupuaçu',
    'Erva-mate': 'erva-mate',
    'Imbú ou umbú': 'umbu',
    'Ipecacuanha (raiz)': 'ipecacuanha-raiz',
    'Jaborandi (folha)': 'jaborandi-folha',
    'Jambu (folha)': 'jambu-folha',
    'Juçara (fruto)': 'juçara-fruto',
    'Lenha': 'lenha',
    'Licuri (cera)': 'licuri-cera',
    'Licuri (coquilho)': 'licuri-coquilho',
    'Macaúba (fruto)': 'macaúba-fruto',
    'Madeira em toras outra finalidade': 'madeira em toras-outra finalidade',
    'Madeira em toras para papel': 'madeira em toras-para papel',
    'Mangaba (fruto)': 'mangaba-fruto',
    'Maniçoba (goma elástica)': 'maniçoba-goma elástica',
    'Maçaranduba (goma não elástica)': 'maçaranduba',
    'Murici': 'murici',
    'Murumuru (semente)': 'murumuru-semente',
    'Oiticica (semente)': 'oiticica-semente',
    'Outros produtos': 'outros produtos',
    'Palmito': 'palmito',
    'Pequi': 'pequi',
    'Piaçava (fibra)': 'piaçava-fibra',
    'Pinhão': 'pinhão',
    'Pupunha (coco)': 'pupunha-coco',
    'Sorva (goma não elástica)': 'sorva',
    'Total': 'total',
    'Tucumã': 'tucumã',
    'Ucuuba (amêndoa)': 'ucuuba-amêndoa'
}

### lAVOURA PERMANENTE

dicionario_produtos_pam_permanente = {
    'Abacate': 'abacate',
    'Açaí': 'açaí-fruto',
    'Algodão arbóreo (em caroço)': 'algodão arbóreo',
    'Azeitona': 'azeitona',
    'Banana (cacho)': 'banana-cacho',
    'Borracha (látex coagulado)': 'borracha-latéx coagulado',
    'Borracha (látex líquido)': 'borracha-latéx líquido',
    'Cacau (em amêndoa)': 'cacau-amêndoa',
    'Café (em grão) Arábica': 'café arábica-grão',
    'Café (em grão) Canephora': 'café canephora-grão',
    'Café (em grão) Total': 'café total-grão',
    'Caju': 'caju',
    'Caqui': 'caqui',
    'Castanha de caju': 'castanha de caju',
    'Chá-da-índia (folha verde)': 'chá da índia',
    'Coco-da-baía*': 'coco da baía',
    'Dendê (cacho de coco)': 'dendê-coco',
    'Erva-mate (folha verde)': 'erva mate',
    'Figo': 'figo',
    'Goiaba': 'goiaba',
    'Guaraná (semente)': 'guaraná',
    'Laranja': 'laranja',
    'Limão': 'limão',
    'Maçã': 'maçã',
    'Mamão': 'mamão',
    'Manga': 'manga',
    'Maracujá': 'maracujá',
    'Marmelo': 'marmelo',
    'Noz (fruto seco)': 'noz',
    'Palmito': 'palmito',
    'Pera': 'pera',
    'Pêssego': 'pêssego',
    'Pimenta-do-reino': 'pimenta do reino',
    'Sisal ou agave (fibra)': 'agave, sisal-fibra',
    'Tangerina': 'tangerina',
    'Total': 'total',
    'Tungue (fruto seco)': 'tungue-fruto seco',
    'Urucum (semente)': 'urucum-semente',
    'Uva': 'uva'
}

dicionario_produtos_censo_6955_2518 = {
    "Abacate": "abacate",
    "Açaí (fruto)": "açaí-fruto",
    "Acerola": "acerola",
    "Agave, sisal (fibra)": "agave, sisal-fibra",
    "Agave, sisal (folha)": "agave, sisal-folha",
    "Algodão arbóreo": "algodão arbóreo",
    "Ameixa": "ameixa",
    "Amora (folha)": "amora-folha",
    "Amora (fruto)": "amora-fruto",
    "Atemoia": "atemoia",
    "Azeitona (oliveira)": "azeitona",
    "Banana": "banana",
    "Borracha (látex coagulado)": "borracha-latéx coagulado",
    "Borracha (látex líquido)": "borracha-latéx líquido",
    "Cacau (amêndoa)": "cacau-amêndoa",
    "Café arábica em grão (verde)": "café arábica-grão",
    "Café canephora (robusta, conilon) em grão (verde)": "café canephora-grão",
    "Caju (castanha)": "caju-castanha",
    "Caju (fruto)": "caju-fruto",
    "Camu-camu": "camu-camu",
    "Caqui": "caqui",
    "Carambola": "carambola",
    "Chá-da-Índia": "chá da índia",
    "Coco-da-baía": "coco da baía",
    "Cravo-da-Índia": "cravo da índia",
    "Cupuaçu": "cupuaçu",
    "Dendê (coco)": "dendê-coco",
    "Erva-mate": "erva-mate",
    "Figo": "figo",
    "Fruta-de-conde": "fruta-de-conde",
    "Goiaba": "goiaba",
    "Graviola": "graviola",
    "Guaraná": "guaraná",
    "Jabuticaba": "jabuticaba",
    "Jaca": "jaca",
    "Jambo": "jambo",
    "kiwi": "kiwi",
    "Laranja": "laranja",
    "Lichia": "lichia",
    "Lima": "lima",
    "Limão": "limão",
    "Louro (folha)": "louro-folha",
    "Maçã": "maçã",
    "Mamão": "mamão",
    "Manga": "manga",
    "Maracujá": "maracujá",
    "Mudas de cacau": "cacau-mudas",
    "Mudas de café": "café-mudas",
    "Mudas de caju": "caju-mudas",
    "Mudas de coco-da-baía": "coco da baía-mudas",
    "Mudas de frutas cítricas (laranja, limão, tangerina, etc.)": "frutas cítricas-mudas",
    "Mudas de mamão": "mamão-mudas",
    "Mudas de outros produtos da lavoura permanente": "outros produtos lavoura permanente-mudas",
    "Mudas de uva": "uva-mudas",
    "Nectarina": "nectarina",
    "Nêspera": "nêspera",
    "Noz (europeia, pecã)": "noz",
    "Outros produtos": "outros-produtos",
    "Palmito": "palmito",
    "Pera": "pera",
    "Pêssego": "pêssego",
    "Pimenta-do-reino": "pimenta-do-reino",
    "Pitaia": "pitaia",
    "Pitanga": "pitanga",
    "Pupunha (cacho frutos)": "pupunha-cacho",
    "Romã": "romã",
    "Tangerina, bergamota, mexerica": "tangerina",
    "Total": "total",
    "Urucum (semente)": "urucum-semente",
    "Uva (mesa)": "uva-mesa",
    "Uva (vinho ou suco)": "uva-vinho"
}


### lAVOURA TEMPORÁRIA
dicionario_produtos_pam_temporaria = {
    "Abacaxi*": "abacaxi",
    "Alfafa fenada": "alfafa-fenada",
    "Algodão herbáceo (em caroço)": "algodão herbáceo",
    "Alho": "alho",
    "Amendoim (em casca)": "amendoim-casca",
    "Arroz (em casca)": "arroz-casca",
    "Aveia (em grão)": "aveia-grão",
    "Batata-doce": "batata-doce",
    "Batata-inglesa": "batata inglesa",
    "Cana-de-açúcar": "cana de açúcar",
    "Cana para forragem": "cana forrageira",
    "Cebola": "cebola",
    "Centeio (em grão)": "centeio-grão",
    "Cevada (em grão)": "cevada-grão",
    "Ervilha (em grão)": "ervilha-grão",
    "Fava (em grão)": "fava-grão",
    "Feijão (em grão)": "feijão-grão",
    "Fumo (em folha)": "fumo-folha",
    "Girassol (em grão)": "girassol-grão",
    "Juta (fibra)": "juta-fibra",
    "Linho (semente)": "linho-semente",
    "Malva (fibra)": "malva-fibra",
    "Mamona (baga)": "mamona-baga",
    "Mandioca": "mandioca",
    "Melancia": "melancia",
    "Melão": "melão",
    "Milho (em grão)": "milho-grão",
    "Rami (fibra)": "rami-fibra",
    "Soja (em grão)": "soja-grão",
    "Sorgo (em grão)": "sorgo-grão",
    "Tomate": "tomate",
    "Total": "total",
    "Trigo (em grão)": "trigo-grão",
    "Triticale (em grão)": "triticale-grão"
}


dicionario_produtos_censo_6957_2337 = {
    "Abacaxi": "abacaxi",
    "Abóbora, moranga, jerimum": "abóbora",
    "Algodão herbáceo": "algodão herbáceo",
    "Alho": "alho",
    "Amendoim em casca": "amendoim-casca",
    "Arroz em casca": "arroz-casca",
    "Aveia branca em grão": "aveia-grão",
    "Batata-inglesa": "batata inglesa",
    "Cana-de-açúcar": "cana de açúcar",
    "Cana forrageira": "cana forrageira",
    "Cebola": "cebola",
    "Centeio em grão": "centeio-grão",
    "Cevada em casca": "cevada-casca",
    "Colza (canola)": "colza-canola",
    "Ervilha em grão": "ervilha-grão",
    "Fava em grão": "fava-grão",
    "Feijão de cor em grão": "feijão de cor-grão",
    "Feijão fradinho em grão": "feijão fradinho-grão",
    "Feijão preto em grão": "feijão preto-grão",
    "Feijão verde": "feijão verde",
    "Forrageiras para corte": "forrageiras para corte",
    "Fumo em folha seca": "fumo-folha",
    "Gergelim (semente)": "gergelim-semente",
    "Girassol (semente)": "girassol-semente",
    "Juta (fibra)": "juta-fibra",
    "Linho (fibra)": "linho-fibra",
    "Malva (fibra)": "malva-fibra",
    "Mamona": "mamona",
    "Mandioca (aipim, macaxeira)": "mandioca",
    "Melancia": "melancia",
    "Melão": "melão",
    "Milho em grão": "milho-grão",
    "Milho forrageiro": "milho-forrageiro",
    "Outros produtos": "outros produtos",
    "Palma forrageira": "palma-forrageira",
    "Rami (fibra)": "rami-fibra",
    "Sementes de algodão (produzidas para plantio)": "algodão-sementes",
    "Sementes de arroz (produzidas para plantio)": "arroz-sementes",
    "Sementes de batata-inglesa (produzidas para plantio)": "batata-sementes",
    "Sementes de feijão (produzidas para plantio)": "feijão-sementes",
    "Sementes de forrageiras (produzidas para plantio)": "forrageiras-sementes",
    "Sementes de milho (produzidas para plantio)": "milho-sementes",
    "Sementes de soja (produzidas para plantio)": "soja-sementes",
    "Sementes de trigo (produzidas para plantio)": "trigo-sementes",
    "Sementes e outras formas de propagação de outros produtos (produzidas para plantio)": "outros-sementes",
    "Soja em grão": "soja-grão",
    "Sorgo em grão": "sorgo-grão",
    "Sorgo forrageiro": "sorgo-forrageiro",
    "Sorgo vassoura": "sorgo-vassoura",
    "Toletes de cana-de-açúcar (produzidas para plantio)": "cana-toletes",
    "Tomate rasteiro (industrial)": "tomate rasteiro-industrial",
    "Total": "total",
    "Trigo em grão": "trigo-grão",
    "Trigo preto em grão": "trigo-preto",
    "Triticale em grão": "triticale-grão"
}
