# -*- coding: utf-8 -*-

#Dicionário para realizar a conversão dos produtos do IBGE para o padrão do projeto

#Dicionários para padronizar os produtos do IBGE para o padrão do projeto
#NOTE: É comum que o nome dos produtos seja acompanhado de 
#NOTE: informações adicionais entre parênteses, como "semente", "fruto", etc.
#! Defini o padrão  {produto}-{informação adicional}


dicionario_produtos_pevs = {
    '1 - Alimentícios': '1-alimentícios',
    '1.1 - Açaí (fruto)': 'açaí-fruto',
    '1.10 - Outros': 'outros alimentícios',
    '1.2 - Castanha-de-caju': 'castanha de caju',
    '1.3 - Castanha-do-pará': 'castanha do pará',
    '1.4 - Erva-mate': 'erva-mate',
    '1.5 - Mangaba (fruto)': 'mangaba-fruto',
    '1.6 - Palmito': 'palmito',
    '1.7 - Pequi (fruto)': 'pequi-fruto',
    '1.8 - Pinhão': 'pinhão',
    '1.9 - Umbu (fruto)': 'umbu',
    '10 - Tanantes': '10-tanantes',
    '10.1 - Angico (casca)': 'angico',
    '10.2 - Barbatimão (casca)': 'barbatimão',
    '10.3 - Outros': 'outros tanantes',
    '2 - Aromáticos, medicinais, tóxicos e corantes': '2-aromáticos, medicinais e corantes',
    '2.1 - Ipecacuanha ou poaia (raiz)': 'ipecacuanha',
    '2.2 - Jaborandi (folha)': 'jaborandi',
    '2.3 - Urucum (semente)': 'urucum',
    '2.4 - Outros': 'outros aromáticos, medicinais e corantes',
    '3 - Borrachas': '3-borrachas',
    '3.1 - Caucho': 'caucho',
    '3.2 - Hevea (látex coagulado)': 'látex hevea-coagulado',
    '3.3 - Hevea (látex líquido)': 'látex hevea-líquido',
    '3.4 - Mangabeira': 'mangabeira',
    '4 - Ceras': '4-ceras',
    '4.1 - Carnaúba (cera)': 'carnaúba-cera',
    '4.2 - Carnaúba (pó)': 'carnaúba-pó',
    '4.3 - Outras': 'outras ceras',
    '5 - Fibras': '5-fibras',
    '5.1 - Buriti': 'buriti',
    '5.2 - Carnaúba': 'carnaúba',
    '5.3 - Piaçava': 'piaçava',
    '5.4 - Outras': 'outras fibras',
    '6 - Gomas não elásticas': '6-gomas não elásticas',
    '6.1 - Balata': 'balata',
    '6.2 - Maçaranduba': 'maçaranduba',
    '6.3 - Sorva': 'sorva',
    '7.1 - Carvão vegetal': 'carvão vegetal',
    '7.2 - Lenha': 'lenha',
    '7.3 - Madeira em tora': 'madeira-tora',
    '8 - Oleaginosos': '8-oleaginosos',
    '8.1 - Babaçu (amêndoa)': 'babaçu-amêndoa',
    '8.2 - Copaíba (óleo)': 'copaíba-óleo',
    '8.3 - Cumaru (amêndoa)': 'cumaru-amêndoa',
    '8.4 - Licuri (coquilho)': 'licuri-coquilho',
    '8.5 - Oiticica (semente)': 'oiticica',
    '8.6 - Pequi (amêndoa)': 'pequi-amêndoa',
    '8.7 - Tucum (amêndoa)': 'tucum-amêndoa',
    '8.8 - Outros': 'outros oleaginosos',
    '9.1 - Pinheiro brasileiro (nó de pinho)': 'pinheiro brasileiro-nó de pinho',
    '9.2 - Pinheiro brasileiro (árvores abatidas)': 'pinheiro brasileiro-árvores abatidas',
    '9.3 - Pinheiro brasileiro (madeira em tora)': 'pinheiro brasileiro-madeira em tora',
    'Total': 'total'
}

dicionario_protudos_censo_6949_2233 = {
    'Andiroba (semente)': 'andiroba-semente',
    'Araticum (fruto)': 'araticum-fruto',
    'Açaí (fruto)': 'açaí-fruto',
    'Babaçu (amêndoa)': 'babaçu-amêndoa',
    'Babaçu (coco)': 'babaçu-coco',
    'Bacaba (fruto)': 'bacaba-fruto',
    'Bacuri': 'bacuri',
    'Baru (amêndoa)': 'baru-amêndoa',
    'Borracha (látex coagulado)': 'borracha-coagulado',
    'Borracha (látex líquido)': 'borracha-líquido',
    'Buriti (coco)': 'buriti-coco',
    'Buriti (palha)': 'buriti-palha',
    'Butiá (fibra)': 'butiá-fibra',
    'Cacau (amêndoa)': 'cacau-amêndoa',
    'Cagaita (fruto)': 'cagaita-fruto',
    'Cajarana': 'cajarana',
    'Camu-camu (fruto)': 'camu camu fruto',
    'Carnaúba (cera)': 'carnaúba-cera',
    'Carnaúba (pó de palha) - Kg': 'carnaúba-pó de palha',
    'Casca de angico': 'angico',
    'Castanha-do-Brasil (castanha-do-Pará)': 'castanha do pará',
    'Caucho (goma elástica)': 'caucho-goma elástica',
    'Copaíba (óleo)': 'copaíba-óleo',
    'Cumaru (semente)': 'cumaru-semente',
    'Cupuaçu': 'cupuaçu',
    'Erva-mate': 'erva-mate',
    'Imbú ou umbú': 'umbu',
    'Ipecacuanha (raiz)': 'ipecacuanha',
    'Jaborandi (folha)': 'jaborandi',
    'Jambu (folha)': 'jambu-folha',
    'Juçara (fruto)': 'juçara-fruto',
    'Lenha': 'lenha',
    'Licuri (cera)': 'licuri-cera',
    'Licuri (coquilho)': 'licuri-coquilho',
    'Macaúba (fruto)': 'macaúba-fruto',
    'Madeira em toras outra finalidade': 'madeira tora-outra finalidade',
    'Madeira em toras para papel': 'madeira tora-papel',
    'Mangaba (fruto)': 'mangaba',
    'Maniçoba (goma elástica)': 'maniçoba-goma-elástica',
    'Maçaranduba (goma não elástica)': 'maçaranduba',
    'Murici': 'murici',
    'Murumuru (semente)': 'murumuru-semente',
    'Oiticica (semente)': 'oiticica-semente',
    'Outros produtos': 'outros produtos',
    'Palmito': 'palmito',
    'Pequi': 'pequi-fruto',
    'Piaçava (fibra)': 'piaçava',
    'Pinhão': 'pinhão',
    'Pupunha (coco)': 'pupunha-coco',
    'Sorva (goma não elástica)': 'sorva',
    'Total': 'total',
    'Tucumã': 'tucumã',
    'Ucuuba (amêndoa)': 'ucuuba-amêndoa'
}

