#!/usr/bin/env python3
"""Generate reproducible charts for the income monetary-correction audit.

The old/current exports are one-row wide CSVs produced by the existing local
comparison workflow. The corrected coefficients and source PIA/PAC tables are
long CSVs generated by the pipeline (or by an in-memory API audit).
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

from dados.gold.br_coeficientes_renda.previsao_renda import ForecastConfig
from dados.gold.br_coeficientes_renda.utils import _projetar_variaveis_brutas


ACCOUNT_FAMILIES = {
    "Produção rural (AA)": ["AAProdução"],
    "Indústria beneficiada": ["AFIndustBenef", "BFIndustBenef", "CFIndustBenef"],
    "Indústria transformação": ["AGIndustTransf", "BGIndustTransf", "CGIndustTransf"],
    "Comércio atacadista": ["AHAtacado", "BHAtacado", "CHAtacado"],
    "Comércio varejista": [
        "ACVarejoRural",
        "AIVarejoUrbano",
        "BIVarejoUrbano",
        "CIVarejoUrbano",
    ],
}


def _read_wide_export(path: Path, version: str) -> pd.DataFrame:
    wide = pd.read_csv(path)
    if len(wide) != 1:
        raise ValueError(f"Esperada uma linha no dump {path}; recebidas {len(wide)}")

    rows = []
    for key, value in wide.iloc[0].items():
        year, account = key.split(".", 1)
        rows.append(
            {
                "ano": int(year),
                "conta_alfa": account,
                "coeff": float(value),
                "versao": version,
            }
        )
    return pd.DataFrame(rows)


def _read_corrected(path: Path) -> pd.DataFrame:
    corrected = pd.read_csv(path)
    required = {"ano", "conta_alfa", "tipo_coeff", "coeff"}
    missing = required.difference(corrected.columns)
    if missing:
        raise ValueError(f"Colunas ausentes nos coeficientes corrigidos: {missing}")
    corrected = corrected.loc[
        corrected["tipo_coeff"].eq("prod_mon_trab"),
        ["ano", "conta_alfa", "coeff"],
    ].copy()
    corrected["versao"] = "corrigida IPCA"
    return corrected


def _family_means(coefficients: pd.DataFrame) -> pd.DataFrame:
    family_by_account = {
        account: family
        for family, accounts in ACCOUNT_FAMILIES.items()
        for account in accounts
    }
    selected = coefficients.loc[
        coefficients["conta_alfa"].isin(family_by_account)
    ].copy()
    selected["familia"] = selected["conta_alfa"].map(family_by_account)
    return (
        selected.groupby(["ano", "versao", "familia"], as_index=False)["coeff"]
        .mean()
        .sort_values(["familia", "versao", "ano"])
    )


def _plot_productivity(family_data: pd.DataFrame, output_path: Path) -> None:
    figure, axes = plt.subplots(3, 2, figsize=(15, 12), sharex=True)
    styles = {
        "antiga": {"linestyle": "--", "linewidth": 1.8},
        "atual sem IPCA": {"linestyle": ":", "linewidth": 2.0},
        "corrigida IPCA": {"linestyle": "-", "linewidth": 2.2},
    }
    colors = {
        "antiga": "#7f7f7f",
        "atual sem IPCA": "#d95f02",
        "corrigida IPCA": "#1b9e77",
    }

    for axis, family in zip(axes.flat, ACCOUNT_FAMILIES, strict=False):
        subset = family_data.loc[family_data["familia"].eq(family)]
        for version, group in subset.groupby("versao", sort=False):
            axis.plot(
                group["ano"],
                group["coeff"],
                label=version,
                color=colors[version],
                **styles[version],
            )
        axis.axvline(2007, color="#bbbbbb", linewidth=1.0, alpha=0.8)
        axis.axvline(2022, color="#4c78a8", linewidth=1.0, alpha=0.7)
        axis.set_title(family)
        axis.grid(alpha=0.2)
        axis.set_ylabel("Coeficiente (mil R$/pessoa/ano; bases distintas)")

    unused = axes.flat[-1]
    unused.axis("off")
    handles, labels = axes.flat[0].get_legend_handles_labels()
    unused.legend(handles, labels, loc="center", frameon=False)
    figure.suptitle(
        "Coeficientes de produtividade: antiga × atual nominal × corrigida pelo IPCA",
        fontsize=15,
    )
    figure.tight_layout(rect=(0, 0, 1, 0.96))
    figure.savefig(output_path, dpi=160, bbox_inches="tight")
    plt.close(figure)


def _employment_projection(source: pd.DataFrame, years: list[int]) -> pd.DataFrame:
    projected = _projetar_variaveis_brutas(
        source,
        years=years,
        value_columns=["pessoal_ocupado_31_12"],
        forecast_config=ForecastConfig(
            method="theil_sen",
            clamp_non_negative=True,
            max_annual_growth_rate=0.5,
        ),
    )
    return projected


def _sum_prefixes(projected: pd.DataFrame, prefixes: set[str]) -> pd.Series:
    selected = projected.loc[
        projected["divisao_grupo_cnae_2"]
        .astype(str)
        .map(lambda code: any(code.startswith(prefix) for prefix in prefixes))
    ]
    return selected.groupby("ano")["pessoal_ocupado_31_12"].sum()


def _plot_employment_inputs(
    pia_path: Path,
    pac_path: Path,
    output_path: Path,
    years: list[int],
) -> None:
    pia = pd.read_csv(pia_path)
    pac = pd.read_csv(pac_path)
    pia_projected = _employment_projection(pia, years)
    pac_projected = _employment_projection(pac, years)

    series = {
        "Indústria (CNAEs usados)": _sum_prefixes(
            pia_projected, {"10", "11", "20"}
        ),
        "Comércio atacadista": _sum_prefixes(pac_projected, {"3"}),
        "Comércio varejista": _sum_prefixes(pac_projected, {"4"}),
    }

    figure, axes = plt.subplots(2, 2, figsize=(14, 9), sharex=True)
    for axis, (label, values) in zip(axes.flat, series.items(), strict=False):
        axis.plot(
            values.index,
            values.values,
            color="#4c78a8",
            linewidth=3.2,
            alpha=0.45,
            label="antes da correção",
        )
        axis.plot(
            values.index,
            values.values,
            color="#1b9e77",
            linestyle="--",
            linewidth=1.8,
            label="após correção (idêntico)",
        )
        axis.axvline(2007, color="#bbbbbb", linewidth=1.0)
        axis.set_title(label)
        axis.set_ylabel("Pessoas ocupadas")
        axis.grid(alpha=0.2)

    total = sum(series.values())
    total_axis = axes.flat[-1]
    total_axis.plot(total.index, total.values, color="#4c78a8", linewidth=3.2, alpha=0.45)
    total_axis.plot(
        total.index,
        total.values,
        color="#1b9e77",
        linestyle="--",
        linewidth=1.8,
    )
    total_axis.axvline(2007, color="#bbbbbb", linewidth=1.0)
    total_axis.set_title("Total das entradas selecionadas")
    total_axis.set_ylabel("Pessoas ocupadas")
    total_axis.grid(alpha=0.2)

    handles, labels = axes.flat[0].get_legend_handles_labels()
    figure.legend(handles, labels, loc="lower center", ncol=2, frameon=False)
    figure.suptitle(
        "Emprego de entrada do preditor: nenhuma correção por IPCA é aplicada",
        fontsize=15,
    )
    figure.tight_layout(rect=(0, 0.06, 1, 0.96))
    figure.savefig(output_path, dpi=160, bbox_inches="tight")
    plt.close(figure)


def _write_summary(family_data: pd.DataFrame, output_path: Path) -> None:
    selected_years = {1995, 2002, 2005, 2006, 2007, 2022, 2023}
    summary = family_data.loc[family_data["ano"].isin(selected_years)].copy()
    summary.to_csv(output_path, index=False)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--old-wide", required=True, type=Path)
    parser.add_argument("--current-wide", required=True, type=Path)
    parser.add_argument("--corrected-long", required=True, type=Path)
    parser.add_argument("--pia-silver", required=True, type=Path)
    parser.add_argument("--pac-silver", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    corrected = _read_corrected(args.corrected_long)
    coefficients = pd.concat(
        [
            _read_wide_export(args.old_wide, "antiga"),
            _read_wide_export(args.current_wide, "atual sem IPCA"),
            corrected,
        ],
        ignore_index=True,
    )
    family_data = _family_means(coefficients)
    _plot_productivity(
        family_data, args.output_dir / "produtividade_coeficientes_comparacao.png"
    )
    years = sorted(coefficients["ano"].unique().astype(int).tolist())
    _plot_employment_inputs(
        args.pia_silver,
        args.pac_silver,
        args.output_dir / "emprego_entrada_auditoria.png",
        years,
    )
    _write_summary(family_data, args.output_dir / "resumo_produtividade.csv")
    corrected.to_csv(
        args.output_dir / "coeficientes_produtividade_corrigidos.csv", index=False
    )


if __name__ == "__main__":
    main()
