-- Implementa arquitetura de zonas
CREATE DATABASE ${DB_RAW_ZONE};
CREATE DATABASE ${DB_TRUSTED_ZONE};
CREATE DATABASE ${DB_AGREGATED_ZONE};
CREATE DATABASE ${DB_OUTPUT_ZONE};


-- Fornece privilégios de Admin para o POSTGRES_USER
GRANT ALL PRIVILEGES ON DATABASE ${DB_RAW_ZONE} TO ${POSTGRES_USER};
GRANT ALL PRIVILEGES ON DATABASE ${DB_TRUSTED_ZONE} TO ${POSTGRES_USER};
GRANT ALL PRIVILEGES ON DATABASE ${DB_AGREGATED_ZONE} TO ${POSTGRES_USER};
GRANT ALL PRIVILEGES ON DATABASE ${DB_OUTPUT_ZONE} TO ${POSTGRES_USER};

