-- Implementa arquitetura de zonas
CREATE DATABASE ${DB_RAW_ZONE};
CREATE DATABASE ${DB_TRUSTED_ZONE};
CREATE DATABASE ${DB_AGREGATED_ZONE};
CREATE DATABASE ${DB_OUTPUT_ZONE};


-- Fornece privilégios de Admin para o POSTGRES_USER
GRANT ALL PRIVILEGES ON DATABASE ${DB_RAW_ZONE} TO ${POSTGRES_USER};
GRANT ALL PRIVILEGES ON DATABASE ${DB_TRUSTED_ZONE} TO ${POSTGRES_USER};
GRANT ALL PRIVILEGES ON DATABASE ${DB_AGREGATED_ZONE} TO ${POSTGRES_USER};
GRANT ALL PRIVILEGES ON DATABASE ${DB_OUTPUT_ZONE} TO ${POSTGRES_USER};

-- Conecta com as bases de dados e cria schemas
\c ${DB_RAW_ZONE}
CREATE SCHEMA IF NOT EXISTS ${DB_RAW_ZONE};

\c ${DB_TRUSTED_ZONE}
CREATE SCHEMA IF NOT EXISTS ${DB_TRUSTED_ZONE};

\c ${DB_AGREGATED_ZONE}
CREATE SCHEMA IF NOT EXISTS ${DB_AGREGATED_ZONE};

\c ${DB_OUTPUT_ZONE}
CREATE SCHEMA IF NOT EXISTS ${DB_OUTPUT_ZONE};